version:  '2'
services:
  orderservice:
    image: 'hiwotret/orderservice:1.3'
    ports:
      - 9086:9090
    build:
      context: .
    container_name: orderservice
    depends_on:
      - orders-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://orders-db:5432/orders
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - PRODUCT_SERVICE_URL=productservice
  productservice:
    image: 'productservice:latest'
    ports:
      - 9085:9085
    build:
      context: .
    container_name: product
    depends_on:
      - postgresdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-db:5432/product
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - PRODUCT_SERVICE_URL=productservice
  orders-db:
    image: 'postgres:latest'
    container_name: orders-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=orders
  product-db:
    image: 'postgres:latest'
    container_name: product-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=product




