server:
  port: 9898

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}/${DATABASE_NAME:cs490-swe-2023-administrator}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${MYSQL_ROOT_PASSWORD:gold}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  application:
    name:  administration-service

eureka:
  client:
    service-url:
      # For running locally
      defaultZone: http://localhost:8761/eureka/
      # For running in Docker
#       defaultZone: http://eureka:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
