#server:
#  port: 8761
#
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
server:
  port: 8761


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost

#server:
#  port: 8761

#eureka:
#  instance:
#    hostname:  eureka-0
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    serviceUrl:
#      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

#eureka:
#  instance:
#    preferIpAddress: true
#    hostname: eureka-0
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
spring:
  application:
    name: eureka-shopping-cart-server
#      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka