spring:
 cloud:
   gateway:
     routes:
       - id: swiggy-app
         uri: lb://SWIGGY-APP
         predicates:
           - Path=/swiggy/**
         filters:
           - AuthenticationFilter


       - id: restaurant-service
         uri: lb://PRODUCT-SERVICE
         predicates:
           - Path=/product/**
         filters:
           - AuthenticationFilter

       - id: identity-service
         uri: lb://ADMINISTRATION-MODULE
         predicates:
           - Path=/api/v1/users/**

 application:
   name: SHOPPING-CART-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/