

spring:
  application:
    name: shopping-cart-api-gateway
  cloud:
   gateway:
     routes:
       - id: product-service
         uri: lb://product-service
         predicates:
           - Path=/api/v1/products/**
         filters:
           - AuthenticationFilter

       - id: administration-service
         uri: lb://administration-service
         predicates:
           - Path=/api/v1/users/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      register-with-eureka: true
  instance:
    hostname: localhost

server:
  port: 9090
