#server:
#  port: 9898
#
##spring:
##  datasource:
##    driver-class-name: com.mysql.cj.jdbc.Driver
##    url: jdbc:mysql://${DB_HOST:localhost}/${DATABASE_NAME:cs490-swe-2023-administrator}?useSSL=false&allowPublicKeyRetrieval=true
##    username: ${DB_USERNAME:root}
##    password: ${MYSQL_ROOT_PASSWORD:gold}
##  jpa:
##    database-platform: org.hibernate.dialect.MySQL5Dialect
##    generate-ddl: true
##    show-sql: true
##    hibernate:
##      ddl-auto: create
#
#  spring:
#    datasource:
#      url: jdbc:mysql://shopping-cart-mysql-db:3306/cs490-swe-2023-administrator?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#      username: root
#      password: password
#      driver-class-name: com.mysql.cj.jdbc.Driver
#    jpa:
#      database-platform: org.hibernate.dialect.MySQL5Dialect
#      hibernate:
#        ddl-auto: create
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQL8Dialect
#
#  application:
#    name:  administration-service
#
#eureka:
#  client:
#    service-url:
#      # For running locally
#      defaultZone: http://eureka-server:8761/eureka/
#      # For running in Docker
##       defaultZone: http://eureka:8761/eureka/
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#    hostname: localhost
server:
  port: 8082
#  jdbc:mysql://localhost:3306/cs490_onlineshopping_cart_db_docker
#jdbc:mysql://onlineshoppingcartdockerdb:3306/cs490_onlineshopping_cart_db_docker
spring:
  #  datasource:
  #    url: jdbc:mysql://cs490-online-shopping-cart-database-instance.cmrjghmuczi9.us-west-1.rds.amazonaws.com:3306/onlineShoppingCartDatabase?user=admin&password=helloworld
  #    username: admin
  #    password: helloworld
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}/${DB_NAME:cs490-swe-2023-administrator}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:gold}

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: user-service
#eureka:
#  client:
#    service-url:
#      # For running locally
##      defaultZone: http://localhost:8761/eureka/
#      # For running in Docker
#       defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#    hostname: eureka-0

#server:
#  port: 9897
#
#spring:
#  datasource:
#    url: jdbc:mysql://cs490-online-shopping-cart-database-instance.cmrjghmuczi9.us-west-1.rds.amazonaws.com:3306/onlineShoppingCartDatabase?user=admin&password=helloworld
#    username: admin
#    password: helloworld
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#  application:
#    name: administration-service
#
#eureka:
#  client:
#    service-url:
#      # For running locally
#      defaultZone: http://localhost:8762/eureka/
#      # For running in Docker
#      # defaultZone: http://eureka-server:8762/eureka/
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#    hostname: localhost
#    prefer-ip-address: true

#  jdbc:mysql://shopping-cart-mysql-db:3306/cs490-swe-2023-administrator?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
