spring:
  application:
    name: PRODUCT-SERVICE

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

#zuul:
#  routes:
#    ADMINISTRATION-MODULE:
#      path: /users/**
#      serviceId: ADMINISTRATION-MODULE
#    PRODUCT-SERVICE:
#      path: /products/**
#      serviceId: PRODUCT-SERVICE

server:
  port: 9799