server:
  port: 8081

spring:
  application:
    name: shopping-cart-api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
            allowed-headers:
              - "*"
            allow-credentials: true
      routes:
        - id: cart-service
          uri: http://shoppingcart-service:8084/
          predicates:
            - Path=/api/v1/cart/**
          filters:
            - AuthenticationFilter

        - id: cart-line-service
          uri: http://shoppingcart-service:8084/
          predicates:
            - Path=/api/v1/cartLine/**
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: http://user-service:8082/
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter

        - id: product-service
          uri: http://product-service:8083/
          predicates:
            - Path=/api/v1/products/**
          filters:
            - AuthenticationFilter

        - id: category-service
          uri: http://product-service:8083/
          predicates:
            - Path=/api/v1/categories/**
          filters:
            - AuthenticationFilter

        - id: order-service
          uri: http://order-service:8085/
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - AuthenticationFilter

        - id: payment-service
          uri: http://payment-service:8086/
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - AuthenticationFilter

        - id: notification-service
          uri: http://notification-service:8088/
          predicates:
            - Path=/notification-service/**
          filters:
            - AuthenticationFilter

        - id: report-service
          uri: http://report-service:8089/
          predicates:
              - Path=/report-service/**
          filters:
            - AuthenticationFilter



