server:
  port: 8081

spring:
  application:
    name: shopping-cart-api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
          filters:
            - AuthenticationFilter

        - id: administration-service
          uri: http://administration-service-svc:8082/
          predicates:
            - Path=/api/v1/users/**

#eureka:
#  client:
#    service-url:
#      # For running locally
#      #      defaultZone: http://localhost:8761/eureka/
#      # For running in Docker
#      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#    hostname: eureka-0

