apiVersion: apps/v1
kind: Deployment
metadata:
  name: administration-service
  labels:
    app: administration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: administration-service
  template:
    metadata:
      labels:
        app: administration-service
    spec:
      containers:
      - name: administration-service
        image: tusimegodwin256/administration-module:latest # Replace with your image name and tag
        imagePullPolicy: Always
        ports:
          - containerPort: 8082
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://cs490-online-shopping-cart-database-instance.cmrjghmuczi9.us-west-1.rds.amazonaws.com:3306/onlineShoppingCartDatabase?user=admin&password=helloworld
          - name: SPRING_DATASOURCE_USERNAME
            value: admin
          - name: SPRING_DATASOURCE_PASSWORD
            value: helloworld
          - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            value: com.mysql.cj.jdbc.Driver
---
apiVersion: v1
kind: Service
metadata:
  name: administration-service
spec:
  selector:
    app: administration-service
  ports:
   - port: 8082
     targetPort: 8082
     protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: administration-service-config
data:
  application.properties: |-
    spring.application.name=administration-service
    spring.datasource.url=jdbc:mysql://mysql:3306/cs490-swe-2023-administrator?useSSL=false
    spring.datasource.username=root
    spring.datasource.password=gold


# eureka:
#     client:
#         service-url:
#             defaultZone: http://eureka-server:8761/eureka
#         fetch-registry: true
#         register-with-eureka: true
#         enabled: false
