apiVersion: apps/v1
kind: Deployment
metadata:
  name:  shopping-cart-api-gateway
  labels:
    app:  shopping-cart-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  shopping-cart-api-gateway
  template:
    metadata:
      labels:
        app: shopping-cart-api-gateway
    spec:
      containers:
        - name: shopping-cart-api-gateway
          image: tusimegodwin256/shopping-cart-api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
spec:
  selector:
    app: shopping-cart-api-gateway
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
  type: LoadBalancer

