apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: syilma/notificationservice:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8088 # port to access the app in the container
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification
#  type: NodePort # LoadBalancer for or NodePort external service
  ports:
    - protocol: TCP
      port: 8088 # port to access the pod
      targetPort: 8088 # must be the same as the containerPort
#      nodePort: 30300 ## for external service port