apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: hiwotret/orderservice:3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8085 # port to access the app in the container
        env: # Setting Environmental Variables
          - name: DB_HOST # Setting Database host address
            value: ecommercedb
          - name: DB_NAME # Setting Database name
            value: ecommerce
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: myvault
                key: DB_USER_NAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: myvault
                key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order
#  type: NodePort # LoadBalancer for or NodePort external service
  ports:
    - protocol: TCP
      port: 8085 # port to access the pod
      targetPort: 8085 # must be the same as the containerPort